# Generated by Django 4.1.3 on 2022-11-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('playlist', models.FileField(upload_to='media/')),
                ('video', models.FileField(upload_to='media/')),
            ],
        ),
    ]
