# Generated by Django 4.1.3 on 2022-11-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.TextField(default='Luke'),
        ),
    ]
